### PR TITLE
Fixed rpm dbpath command

### PR DESCRIPTION
**Pull request by abaluha-hubs**
Closes: https://github.com/rapid7/docker-image-analyzer/issues/4

--

Image was created with this dockerfile and only has the rpm database copied to it
from the upstream centos image
```
FROM docker.io/library/centos:centos6.10
FROM scratch
COPY --from=0 /var/lib/rpm /var/lib/rpm
COPY --from=0 /etc/centos-release /etc/os-release
COPY --from=0 /etc/centos-release /etc/centos-release
```

It might also be worth pinning this https://github.com/rapid7/docker-image-analyzer/pull/5/files#diff-1cfa027b13a2c3fd088201061a9c6b40R26 to a specific digest, so that changes in `latest` don't cause breakages

### CODE REVIEW

**Comment by gschneider-r7** [comment]
I'm wondering if the image tar file used for testing can be reduced in size. Otherwise this change looks good so far.

**Comment by abaluha-hubs** [comment]
that's probably about as small as we're going to be able to get it. I've also got a case open for this ticket in your support portal, the ID is **00268062**, if that's useful for you

**Comment by gschneider-r7** [comment]
Thanks for submitting the changes. I'm going to work on releasing this today and updating the downstream projects.

**Comment by abaluha-hubs** [comment]
did that end up fixing this issue int he container scanner? I'm having some issues with it still locally, but I was never able to test this fix with it on my machine because I couldn't overwrite it's dependency on this project (assuming it has one). I see this error when I try to use the container scanner now 
```
400 Bad Request
```

with a command like
```
docker run -it -v "${PWD}/test_image.tar":/newFile.tar rapid7/container-image-scanner:latest -f newFile.tar -k "myKey" -r us
```

**Pull request merged**
